import ReportTable from "@/components/ReportTable";

export default function DashboardPage() {
  return (
    <div className="container flex" style={{ flexDirection: 'column', gap: '2rem' }}>
      <header className="flex justify-between items-center" style={{ flexWrap: 'wrap', gap: '1rem' }}>
        <div>
          <h1 style={{ fontSize: '1.875rem', fontWeight: 600, letterSpacing: '-0.025em' }}>Research Dashboard</h1>
          <p style={{ color: 'var(--text-secondary)', marginTop: '0.25rem' }}>Browse the latest equity reports generated by the Research API.</p>
        </div>
      </header>

      <ReportTable />
    </div>
  );
}
